// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Cordango and contributors.
// Part of Cordango, the open application language and compiler: https://github.com/cordango/cordango
// Licensed under the Apache License, Version 2.0. See LICENSE in the repository root.

using Cordango.TestCorpus;

namespace Cordango.Compiler.Tests;

/// <summary>
/// Every source file in this repository says what it is and how it is licensed.
///
/// <para>A LICENSE at the root covers the repository; it does not travel with a file somebody copies
/// into their own project, and copying is exactly what an Apache-2.0 toolchain invites. The header is
/// removable, which is fine — the point is that removing it is a deliberate act rather than the
/// default state of a file nobody stamped.</para>
///
/// <para>A one-time sweep would rot within a slice, so this is a test: add a file without the header
/// and the suite says so, in the same run that would have caught a broken gate.</para>
/// </summary>
public class LicenceHeaderTests
{
    private const string Marker = "SPDX-License-Identifier: Apache-2.0";

    /// <summary>
    /// The Budget Planner specimen is EXAMPLE APPLICATION SOURCE — what a person would write to
    /// describe their own app — and it is regenerated by <c>generate.mjs</c> and reconstructed by
    /// <c>verify.py</c>. Stamping our copyright on it says the wrong thing twice: it claims authorship
    /// of the example a reader is meant to copy, and it puts our header on files an app author's own
    /// tooling emits. The Python and JavaScript TOOLS that live in that directory are ours and are
    /// stamped; the <c>.cord.ts</c> and config files it operates on are not.
    /// </summary>
    private static bool IsExampleApplicationSource(string relative) =>
        relative.Contains("/corpus/semantic/", StringComparison.Ordinal)
        && (relative.EndsWith(".cord.ts", StringComparison.Ordinal)
            || relative.EndsWith("cord.config.ts", StringComparison.Ordinal));

    /// <summary>
    /// The standalone scaffold's templates are the USER's application, not ours.
    ///
    /// <para>Everything under <c>Cordango.Standalone/Templates/</c> is emitted verbatim into a
    /// generated application as that application's own source: its <c>Program.cs</c>, its Vue shell,
    /// the files its owner edits on day one. Stamping our copyright on them claims something untrue
    /// about code we are handing over unencumbered — the same argument as the specimen above, one
    /// layer further out.</para>
    ///
    /// <para>The rest of <c>Cordango.Standalone</c> is the opposite case and stays stamped. It is
    /// our runtime, Apache-2.0, and it is copied into a user's repository, which is precisely the
    /// situation a per-file notice exists for. ScaffoldTests asserts both halves of this from the
    /// other direction: runtime files carry the header, template files must not.</para>
    /// </summary>
    private static bool IsScaffoldTemplate(string relative) =>
        relative.Contains("/Cordango.Standalone/Templates/", StringComparison.Ordinal);

    public static TheoryData<string> SourceFiles()
    {
        var root = Corpus.RepoRoot();
        var data = new TheoryData<string>();

        foreach (var path in Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories))
        {
            var relative = Path.GetRelativePath(root, path).Replace('\\', '/');
            if (relative.Contains("/bin/", StringComparison.Ordinal)
                || relative.Contains("/obj/", StringComparison.Ordinal)
                || relative.Contains("/node_modules/", StringComparison.Ordinal)
                || relative.StartsWith(".git", StringComparison.Ordinal))
                continue;

            var extension = Path.GetExtension(path);
            if (extension is not (".cs" or ".py" or ".js" or ".mjs" or ".ts" or ".vue")) continue;
            if (IsExampleApplicationSource(relative)) continue;
            if (IsScaffoldTemplate(relative)) continue;

            data.Add(relative);
        }

        return data;
    }

    [Theory]
    [MemberData(nameof(SourceFiles))]
    public void Every_source_file_carries_the_licence_header(string relative)
    {
        var path = Path.Combine(Corpus.RepoRoot(), relative.Replace('/', Path.DirectorySeparatorChar));

        // Only the top of the file: a match further down is a mention, not a header, and a header
        // buried under fifty lines is not doing the job a header does.
        var head = string.Join('\n', File.ReadLines(path).Take(8));

        Assert.True(head.Contains(Marker, StringComparison.Ordinal),
            relative + " has no licence header. Every source file in this repository carries one — "
            + "see any neighbouring file for the four lines, and note that a shebang stays first.");
    }

    /// <summary>Guards the guard. An exemption that silently matched everything, or a glob that
    /// silently matched nothing, would leave this class passing while checking air. A floor rather
    /// than an exact count, because adding a file is the ordinary case and should not fail a
    /// suite — the tree held 166 stamped files when this was written.</summary>
    [Fact]
    public void The_sweep_actually_finds_the_repository()
    {
        Assert.True(SourceFiles().Count > 150, "expected the whole source tree, got " + SourceFiles().Count);
    }
}
