// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Cordango and contributors.
// Part of Cordango, the open application language and compiler: https://github.com/cordango/cordango
// Licensed under the Apache License, Version 2.0. See LICENSE in the repository root.

using System.Text.Json.Nodes;

namespace Cordango.Cord;

/// <summary>The screen wire shape → the model. Same rules as <see cref="CordWire"/>: nothing mechanical
/// reaches the author. There is no block, no container, no view key and no page key on this wire —
/// all four are generated by <see cref="CordLowerScreens"/>.</summary>
internal static class CordWireScreens
{
    public static CordScreen Screen(JsonObject o) => new(
        Key: Str(o, "key"),
        Label: Str(o, "label"),
        Subject: Str(o, "subject"),
        Sections: o["sections"] is JsonArray s
            ? s.OfType<JsonObject>().Select(Section).ToList()
            : null,
        Tabs: o["tabs"] is JsonArray t
            ? t.OfType<JsonObject>().Select(Tab).ToList()
            : null);

    public static CordTab Tab(JsonObject o) => new(
        Key: Str(o, "key") ?? "",
        Label: Str(o, "label"),
        Sections: o["sections"] is JsonArray s
            ? s.OfType<JsonObject>().Select(Section).ToList()
            : null);

    private static CordSection Section(JsonObject o) => new(
        Key: Str(o, "key"),
        Kind: Str(o, "kind"),
        Of: Str(o, "of"),
        Label: Str(o, "label"),
        View: Str(o, "view"),
        Filter: o["filter"] is JsonArray f ? f.OfType<JsonObject>().Select(When).ToList() : null,
        Sort: o["sort"] is JsonArray s ? s.OfType<JsonObject>().Select(Sort).ToList() : null,
        Columns: Strings(o, "columns"),
        DateField: Str(o, "dateField"),
        GroupBy: Str(o, "groupBy"),
        Value: o["value"] is JsonObject v && Str(v, "op") is { } op
            ? new CordMeasure(op, Str(v, "field"), Str(v, "groupBy"))
            : null,
        Text: Str(o, "text"),
        // A split's two sides are read by the same function that read this one. The schema fixes the
        // count at two; that they are CONTENT and not more arrangement is CordCheck's job — see
        // CordErrorCode.NestedSplit for why that line falls where it does.
        Sections: o["sections"] is JsonArray sub
            ? sub.OfType<JsonObject>().Select(Section).ToList()
            : null,
        Ratio: o["ratio"] is JsonArray r
            ? r.OfType<JsonValue>().Select(x => x.TryGetValue<double>(out var d) ? d : 0).ToList()
            : null,
        Visual: Str(o, "visual"));

    private static CordWhen When(JsonObject o) =>
        new(Str(o, "field"), Str(o, "operator"), o["value"]?.DeepClone());

    private static CordSort Sort(JsonObject o) =>
        new(Str(o, "field") ?? "", Str(o, "direction"));

    private static string? Str(JsonObject o, string key) =>
        o[key] is JsonValue v && v.TryGetValue<string>(out var s) ? s : null;

    private static List<string>? Strings(JsonObject o, string key) =>
        o[key] is JsonArray a
            ? a.OfType<JsonValue>().Select(v => v.TryGetValue<string>(out var s) ? s : null)
                .Where(s => s is not null).Select(s => s!).ToList()
            : null;
}
