// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Cordango and contributors.
// Part of Cordango, the open application language and compiler: https://github.com/cordango/cordango
// Licensed under the Apache License, Version 2.0. See LICENSE in the repository root.

using System.Text.Json.Nodes;

namespace Cordango.Definition;

/// <summary>
/// The human-readable text inside an App Definition, addressed by PATH.
///
/// <para>This is the foundation of the definition's localization (step 2 — see
/// <c>_docs/LOCALIZATION.md</c>). The definition itself stays single-language: it is written in one
/// authoring language, diffed in one language, and generated by the model in one language. A
/// TRANSLATION BUNDLE sits beside it — a flat <c>path → text</c> map per locale — and the compiler
/// applies the bundle on the way to the manifest.</para>
///
/// <para>Why a sidecar rather than inline <c>{ "en": …, "de": … }</c> values: every label in the
/// schema would become a union of string-or-object, and the Gate, the standalone editor, the shared
/// blockspec and the generator's tool schema would all have to learn both shapes. A path map changes
/// none of them. It also means a translation can be regenerated wholesale when the definition
/// changes, and that an untranslated app is a bundle with fewer entries rather than a definition in
/// a broken state.</para>
///
/// <para>Why not a whole second definition per locale: two documents drift. Nothing would stop the
/// German copy from growing a field the English one does not have, and then the two apps have
/// different data models under one name.</para>
/// </summary>
public static class DefinitionText
{
    /// <summary>
    /// The property names that hold text a HUMAN reads, anywhere in the document.
    ///
    /// <para>Deliberately a name list rather than a set of schema pointers. The schema has ~56
    /// distinct <c>label</c> declarations across block kinds, and enumerating their pointers would
    /// mean this file had to be edited every time a block gains one. The names below are reserved
    /// for display text throughout the schema — a machine value is a <c>key</c>, an <c>entity</c>,
    /// a <c>field</c> or a <c>value</c>, never a <c>label</c>.</para>
    /// </summary>
    private static readonly HashSet<string> TextProperties = new(StringComparer.Ordinal)
    {
        "label", "labelPlural", "title", "subtitle", "description", "placeholder", "hint",
        "emptyText", "empty", "successMessage", "helpText", "caption", "text",
    };

    /// <summary>
    /// Property names that look like text and are NOT.
    ///
    /// <para><c>name</c> is the trap: on the app itself it is the display name, but it is also the
    /// property name inside several machine-facing structures. It is handled by path (below), not by
    /// this list, and everything here is excluded outright.</para>
    /// </summary>
    private static readonly HashSet<string> NeverText = new(StringComparer.Ordinal)
    {
        // A select option's `value` is the STORED code; its `label` beside it is the display text.
        // Translating the value would rewrite the data.
        "value", "key", "entity", "field", "targetEntity", "targetApp", "icon", "color", "type",
        "kind", "format", "expr", "role", "roleKey", "handle", "slug", "state", "stateField",
    };

    /// <summary>Extra document paths that ARE text but whose property name is ambiguous.</summary>
    private static readonly HashSet<string> ExtraPaths = new(StringComparer.Ordinal)
    {
        "name",             // the app's display name — a machine identity lives in `key`
    };

    /// <summary>One translatable string: where it lives, and what it currently says.</summary>
    /// <param name="Path">A slash path from the document root, e.g.
    /// <c>entities/2/fields/5/label</c>. Positional rather than key-based on purpose: an entity's
    /// key can be renamed, and a path that survived a rename by pointing at the wrong element would
    /// silently mistranslate. A path that stops resolving is a MISS, which is visible.</param>
    public readonly record struct Entry(string Path, string Text);

    /// <summary>
    /// Every human-readable string in a definition, in document order.
    ///
    /// <para>Used three ways: to build the translator's worklist, to detect what a definition change
    /// invalidated (a path whose source text moved on), and to assert in tests that a bundle covers
    /// the document.</para>
    /// </summary>
    public static IReadOnlyList<Entry> Extract(JsonNode? definition)
    {
        var entries = new List<Entry>();
        if (definition is not null) Walk(definition, "", entries);
        return entries;
    }

    private static void Walk(JsonNode node, string path, List<Entry> into)
    {
        switch (node)
        {
            case JsonObject obj:
                foreach (var (name, child) in obj)
                {
                    if (child is null) continue;
                    var childPath = path.Length == 0 ? name : $"{path}/{name}";
                    if (child is JsonValue value && value.TryGetValue<string>(out var text))
                    {
                        if (IsText(name, path) && !string.IsNullOrWhiteSpace(text))
                            into.Add(new Entry(childPath, text));
                    }
                    else Walk(child, childPath, into);
                }
                break;
            case JsonArray array:
                for (var i = 0; i < array.Count; i++)
                    if (array[i] is { } item) Walk(item, $"{path}/{i}", into);
                break;
        }
    }

    private static bool IsText(string property, string parentPath)
    {
        if (NeverText.Contains(property)) return false;
        if (TextProperties.Contains(property)) return true;
        // `name` only at the document root — the app's own display name.
        return ExtraPaths.Contains(property) && parentPath.Length == 0;
    }

    /// <summary>
    /// Apply a translation bundle to a definition, returning a NEW document.
    ///
    /// <para>Paths in the bundle that no longer resolve are skipped rather than created: the
    /// definition is the shape, and a stale bundle must not be able to invent structure in it. Paths
    /// the bundle does not cover keep the authoring language, so a half-translated app is a mix
    /// rather than a page full of blanks — which is the right failure, because a missing German
    /// label is still readable and an empty one is not.</para>
    /// </summary>
    /// <returns>The localized document, and how many entries were applied vs skipped.</returns>
    public static (JsonNode Document, int Applied, int Skipped) Apply(
        JsonNode definition, IReadOnlyDictionary<string, string> bundle)
    {
        ArgumentNullException.ThrowIfNull(definition);
        var doc = definition.DeepClone();
        int applied = 0, skipped = 0;

        foreach (var (path, text) in bundle)
        {
            if (string.IsNullOrWhiteSpace(text)) { skipped++; continue; }
            if (Resolve(doc, path) is { } slot && TrySet(slot.Parent, slot.Name, slot.Index, text)) applied++;
            else skipped++;
        }
        return (doc, applied, skipped);
    }

    private readonly record struct Slot(JsonNode Parent, string? Name, int Index);

    /// <summary>Walk a slash path to the node that HOLDS the value, so it can be replaced in place.</summary>
    private static Slot? Resolve(JsonNode root, string path)
    {
        var segments = path.Split('/', StringSplitOptions.RemoveEmptyEntries);
        if (segments.Length == 0) return null;

        var current = root;
        for (var i = 0; i < segments.Length - 1; i++)
        {
            current = Step(current, segments[i]);
            if (current is null) return null;
        }

        var last = segments[^1];
        return int.TryParse(last, out var index)
            ? current is JsonArray arr && index >= 0 && index < arr.Count ? new Slot(current, null, index) : null
            : current is JsonObject obj && obj.ContainsKey(last) ? new Slot(current, last, -1) : null;
    }

    private static JsonNode? Step(JsonNode node, string segment) =>
        int.TryParse(segment, out var index)
            ? node is JsonArray arr && index >= 0 && index < arr.Count ? arr[index] : null
            : node is JsonObject obj && obj.TryGetPropertyValue(segment, out var child) ? child : null;

    private static bool TrySet(JsonNode parent, string? name, int index, string text)
    {
        switch (parent)
        {
            case JsonObject obj when name is not null:
                // Only ever REPLACE a string. A bundle that points at an object or an array is
                // pointing at structure, and overwriting structure with a sentence is how a
                // definition becomes unloadable.
                if (obj[name] is not JsonValue existing || !existing.TryGetValue<string>(out _)) return false;
                obj[name] = JsonValue.Create(text);
                return true;
            case JsonArray arr when index >= 0:
                if (arr[index] is not JsonValue item || !item.TryGetValue<string>(out _)) return false;
                arr[index] = JsonValue.Create(text);
                return true;
            default:
                return false;
        }
    }

    /// <summary>
    /// What a bundle no longer covers, and what it covers that no longer exists.
    ///
    /// <para>The maintenance question, answered without a model: after a definition is edited, which
    /// strings are new (need translating), and which bundle entries are pointing at text that has
    /// since changed underneath them (need re-translating)? Both are far more common than a full
    /// re-translation, and both are cheap to compute.</para>
    /// </summary>
    /// <param name="sourceHashes">The bundle's record of what each path SAID when it was translated
    /// (see the <c>source</c> map in the bundle format). A path whose text has moved on is stale.</param>
    public static (IReadOnlyList<string> Missing, IReadOnlyList<string> Stale, IReadOnlyList<string> Orphaned)
        Diff(JsonNode definition, IReadOnlyDictionary<string, string> bundle,
             IReadOnlyDictionary<string, string>? sourceHashes = null)
    {
        var entries = Extract(definition);
        var paths = entries.ToDictionary(e => e.Path, e => e.Text, StringComparer.Ordinal);

        var missing = entries.Where(e => !bundle.ContainsKey(e.Path)).Select(e => e.Path).ToList();
        var orphaned = bundle.Keys.Where(p => !paths.ContainsKey(p)).ToList();
        var stale = sourceHashes is null
            ? []
            : bundle.Keys
                .Where(p => paths.TryGetValue(p, out var now)
                            && sourceHashes.TryGetValue(p, out var then)
                            && !string.Equals(now, then, StringComparison.Ordinal))
                .ToList();

        return (missing, stale, orphaned);
    }
}
