// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Cordango and contributors.
// Part of Cordango, the open application language and compiler: https://github.com/cordango/cordango
// Licensed under the Apache License, Version 2.0. See LICENSE in the repository root.

using System.Text;
using System.Text.Json.Nodes;
using Cordango.Cord;

namespace Cordango.Cli.Templates;

/// <summary>
/// What <c>cordango new</c> and <c>cordango add app</c> put on disk.
///
/// <para><b>The starter app is built through the pipeline, never copied from a string of files.</b>
/// It is defined here as operations, applied to an empty app, validated, and written by
/// <see cref="CordSource"/> — so a scaffold that no longer passes <c>cordango check</c> fails at
/// <c>cordango new</c> rather than handing somebody a broken workspace to debug. Hand-written template
/// files rot silently the first time the schema moves; these cannot.</para>
/// </summary>
public static class Scaffold
{
    /// <summary>
    /// A minimal task list: one entity, one screen. CordyOSS §2 asks for "a small example, not a
    /// large demo the user must delete" — the first thing a person does here is change it, so it has
    /// to be shorter to read than to replace.
    /// </summary>
    public static JsonArray StarterOps() => (JsonArray)JsonNode.Parse("""
        [
          {"op":"upsert_entity","entity":{
            "key":"task","label":"Task","labelPlural":"Tasks","displayField":"title",
            "fields":[
              {"key":"title","label":"Title","type":"text","required":true},
              {"key":"notes","label":"Notes","type":"longtext"},
              {"key":"due_on","label":"Due","type":"date"},
              {"key":"done","label":"Done","type":"boolean"}
            ]}},
          {"op":"upsert_screen","screen":{
            "key":"tasks","label":"Tasks",
            "sections":[
              {"key":"outstanding","kind":"metric","of":"task","label":"Open",
               "value":{"op":"count"},"filter":[{"field":"done","operator":"eq","value":false}]},
              {"key":"all","kind":"list","of":"task","label":"Everything",
               "columns":["title","due_on","done"],"sort":[{"field":"due_on","direction":"asc"}]}
            ]}}
        ]
        """)!;

    /// <summary>
    /// A directory name as a stable app key.
    ///
    /// <para>Hyphens become underscores because the key is an identifier in the App Definition while
    /// the folder name is prose. They are allowed to differ — <c>doctor</c> only mentions it — but
    /// making the common case agree means nobody has to think about which one a reference uses.</para>
    /// </summary>
    public static string KeyFor(string directoryName)
    {
        var key = new StringBuilder();
        foreach (var c in directoryName.ToLowerInvariant())
        {
            if (char.IsAsciiLetterOrDigit(c)) key.Append(c);
            else if (key.Length > 0 && key[^1] != '_') key.Append('_');
        }

        var text = key.ToString().Trim('_');
        if (text.Length == 0) text = "app";

        // An identifier cannot start with a digit, and "1099-filing" is a perfectly reasonable folder.
        return char.IsAsciiDigit(text[0]) ? "app_" + text : text;
    }

    /// <summary>Title Case from a folder name, for the app's display label.</summary>
    public static string LabelFor(string directoryName)
    {
        var words = directoryName
            .Split(['-', '_', ' '], StringSplitOptions.RemoveEmptyEntries)
            .Select(w => char.ToUpperInvariant(w[0]) + w[1..]);

        var label = string.Join(' ', words);
        return label.Length == 0 ? "App" : label;
    }

    /// <summary>
    /// Both build outputs are ignored, and <c>generated/</c> is the one worth arguing about.
    ///
    /// <para>It holds whole applications — an api, a web front end, a Dockerfile — and they look
    /// exactly like something you would commit. They are reproducible from the source beside them
    /// by a pinned toolchain version, so committing them would double every review and put the
    /// merge conflicts in the half nobody wrote. When an application is ready to have a life of its
    /// own, it moves out of this repository and gets a remote of its own; that is the moment to stop
    /// ignoring it, and it is a deliberate one.</para>
    /// </summary>
    public const string GitIgnore = """
        # Build output. Generated by `cordango build`, never source.
        .cordango/

        # Generated applications, one directory per app. Reproducible from the source beside them.
        generated/

        # Interrupted atomic writes.
        *.tmp[0-9]*
        """;

    /// <summary>
    /// LF for <c>.cordango</c> files, without exception.
    ///
    /// <para>Canonical content is LF. A Windows checkout that converted to CRLF would make every
    /// file read as modified, so <c>cordango fmt</c> would rewrite the whole tree on every run and no
    /// diff would ever be small. One line of config prevents an entire class of "why is everything
    /// changed".</para>
    /// </summary>
    public const string GitAttributes = """
        *.yaml   text eol=lf
        *.md     text eol=lf
        """;

    public static string Readme(string workspaceName, string appDirectory) => $"""
        # {workspaceName}

        A Cordango workspace. One repository is one installation: the apps under `apps/` share
        People, Organizations and Calendar, and they are built, reviewed and deployed together.

        ```
        cordango check        # parse, lower and validate every app
        cordango inspect      # what is in here
        cordango configure    # where these apps run. Asked once, committed
        cordango build        # do what configure said
        ```

        A generated application lands in `generated/<app>/` — an api, a web front end and a
        Dockerfile, yours to run. It is build output and gitignored: everything in it comes from the
        source under `apps/`. Move the directory out when it is ready to have a life of its own.

        The first app is in [`{appDirectory}`]({appDirectory}). Change it or delete it.

        **One workspace holds many apps.** `cordango add app <name>` adds another under `apps/`; they
        share People, Organizations and Calendar, reference each other's records, and are checked,
        built and deployed together. `cordango new` is only for creating the workspace itself.

        **People, Organizations and Calendar are already there.** They are core apps the platform
        provides — `core_people`, `core_organizations`, `core_calendar`. Point at them instead of
        declaring your own company or contact entity:

        ```
        cordango inspect                          # lists them, with their entity keys
        cordango vocabulary core organizations    # what one of them holds
        ```

        A field pointing at one is `type: reference` with `targetApp: core_organizations` and
        `target: organization`. Nothing about this needs an instance or a login.

        Semantic source lives in `.cordango.yaml` files, one per aggregate — an entity, a lifecycle, a role, a
        screen. They are the source of truth. `.cordango/` (with the leading dot) is build output and is
        not committed.
        """;

    /// <summary>
    /// The agent instructions, written to <c>CLAUDE.md</c> and <c>AGENTS.md</c> alike.
    ///
    /// <para><b>Both files get the same text, generated from here.</b> Two conventions want two
    /// filenames, and a workspace that taught Claude and Codex different rules would produce source
    /// only one of them could maintain. They are generated artifacts with one origin, so the
    /// duplication cannot drift.</para>
    ///
    /// <para><b>It teaches the WORKFLOW, not the schema.</b> CordyOSS §8.1 and §8.3: an agent should
    /// arrive knowing how to find out, not carrying a copy of the vocabulary. Everything specific is
    /// one <c>cordango inspect</c> away, and keeping it that way is what stops the prompt growing back
    /// into the 208 KB schema this whole layer exists to avoid.</para>
    /// </summary>
    public static string AgentInstructions(string workspaceName) => $$"""
        # {{workspaceName}}

        This is a Cordango workspace. The apps under `apps/` are defined by **semantic source** —
        `.cordango.yaml` files describing entities, workflows, roles and screens. `cordango` turns them into a
        running application.

        ## Start with questions, not with an entity

        The person asking for an app knows their work and does not know this language. You know the
        language and nothing about their work. Almost every bad generated app comes from closing that
        gap by guessing.

        So before you write a single entity, ask. Not a questionnaire — two or three questions, then
        say back what you heard and ask the next two. Keep going until you can answer these yourself:

        - **What is the record?** The thing there are many of, that somebody counts at the end of the
          month. A claim, a shift, a deal, a machine. Most apps have one, plus the things that hang
          off it.
        - **Who touches it, and what may each of them do?** "Everyone" is an answer that produces an
          app with no roles and no reason to sign in. Ask for the job titles.
        - **What states does it move through, and what moves it?** Draft, submitted, approved is a
          workflow. Who presses the button, and what has to be true before they may?
        - **What does somebody open first thing in the morning?** That is the home screen. If nobody
          can name it, the app does not yet have a landing page worth building.
        - **What must never happen?** An approval by the person who filed it. Two bookings on one
          room. These become guards, not a paragraph in a README.
        - **What already exists?** Before modelling a company, a person or a calendar event, read
          "Some things already exist" below — and then ask which of theirs is one of those.
        - **What gets counted?** Anything totalled, averaged, aged or ranked is a computed field or a
          rollup, and both are far easier to model at the start than to add later over a shape that
          assumed nobody would ask.

        Ask about the WORK, never about the schema. "Does a claim ever get reopened after it is
        paid?" is a question they can answer. "Should status be a select or a reference?" is not, and
        it is your job anyway.

        Two more rules about asking:

        - **Ask when the answer changes what you build.** Do not ask permission for the obvious.
        - **Say what you assumed.** When something is unclear and small, choose, build it, and name
          the assumption in the same message. Being corrected is cheap. Being blocked is not.

        ## Before you change anything

        ```
        cordango inspect                        # the apps in this workspace
        cordango inspect --app <key>            # one app
        cordango inspect entities/claim --app <key>   # one aggregate
        ```

        Inspect the aggregate you are about to touch. Do not read every file in the repository — the
        point of this layout is that you never need to.

        ## Finding out what may be written

        ```
        cordango vocabulary                     the words, and what exists
        cordango vocabulary field               a field's properties and its types
        cordango vocabulary block calendar      what a calendar block accepts
        cordango vocabulary core organizations  what a core app holds
        ```

        **Never read the `cordango` binary, and never go looking for the App Definition schema.** If
        `cordango vocabulary` cannot answer your question, that is a missing feature in cordango — say so
        rather than working around it.

        ## Some things already exist — link to them

        ```
        cordango discover                       what every app here and on the instance offers
        cordango discover supplier              the apps that answer a question, ranked
        cordango discover --app <key>           one app in full
        cordango discover won --events          which app announces what
        ```

        **Run this before you model anything.** It lists every app's entities, the events it
        announces, the actions it offers and the rules those actions carry — this workspace's apps
        always, and the rest of the instance's when you are logged in. If a concept already exists
        somewhere, reference it or build on its events instead of declaring a second copy. A duplicate
        entity is valid Cord, so nothing will refuse it; this command is how you find out in time.

        People, Organizations and Calendar are **core apps** the platform provides to every
        workspace. They are not in this repository and you will not find them by reading files, so
        `cordango discover` and `cordango inspect` list them for you along with their entity keys.

        Before declaring an entity, check whether it is one of these. A company, a customer, a
        supplier, an employee, a calendar event: these already have a canonical record, and a second
        copy is the one mistake this layout cannot undo for you later. To point at one:

        ```
        type: reference   targetApp: core_organizations   target: organization
        ```

        The entity key is not always the label — Organizations calls `organization` a "Company".
        `cordango vocabulary core organizations` gives you both, plus every field it already carries.

        This workspace has two halves and it is worth knowing which one you are in:

        - `entities/`, `workflows/`, `roles/` are **semantic**. Small vocabulary, listed under
          `cordango vocabulary` with no arguments. You will rarely need more than that.
        - `views/` are still **App Definition block trees** — screens are not modelled semantically
          yet. That is where `cordango vocabulary block <kind>` earns its place. Ask for one kind at a
          time; asking for everything defeats the point of the layer.

        ## Changing an app

        Two ways, both supported:

        **Semantic operations** (preferred for structural change):

        ```
        cordango apply ops.json --app <key> --scope domain
        cordango apply - --app <key> --scope screen:claims     # ops on stdin
        ```

        `--scope` names the one aggregate the change may touch. Kinds: `domain`, `behaviour`,
        `access`, `screen:<key>`, `tab:<screen>/<tab>`. An operation naming anything else is refused
        and **no file is written** — so a rejected attempt costs nothing and needs no cleanup.
        Add `--dry-run` to see which files a change would rewrite.

        **Editing `.cordango.yaml` files directly** is fine too. They describe what a thing IS, not
        the steps that built it, and both paths assemble into the same model.

        ## After you change anything

        ```
        cordango check --app <key>
        ```

        Two outcomes that are not the same thing:

        - **not coherent** — the app does not hold together. This is an error. Fix it.
        - **coherent, incomplete** — it holds together but is not a finished application yet (no
          screen to land on, nothing to create). Normal mid-build. Keep going.

        `cordango check` never calls a model and never touches a database. Run it freely.

        ## Where this workspace builds

        `cordango.yaml` carries a `build:` block saying where these apps are meant to run. It is the
        reason `cordango build` needs no flags.

        ```
        cordango configure --show                 what is set, if anything
        cordango configure --target standalone
        cordango build
        ```

        Two targets:

        - **standalone** — a repository of its own: ASP.NET Core, Vue, PostgreSQL, a Dockerfile,
          written to `generated/<app-key>/`. That path is not configurable and there is no `--out`;
          the directory is gitignored build output, and moving it out of the repository is how an
          application leaves. It belongs to them: delete cordango afterwards and it still builds.
        - **platform** — published to a Cordango instance with `cordango publish`. It needs a
          connection, and `configure` and `build` both refuse without one — on the platform an app
          can see the other apps in the workspace and the core apps, and none of that is knowable
          offline. `cordango login <token>` connects it.

        Publishing has a way back. `cordango import` with no argument lists the apps on the connected
        instance and asks which one; `cordango import --list` just looks, and
        `cordango import <handle>` brings one in as source under `apps/`. That is how an app built in
        Studio, or published from somebody else's checkout, becomes files you can read and edit. A
        file works with no connection at all: `cordango import <app.definition.json>`.

        If there is no `build:` block, **ask which one they want before the first build**, the same
        way you asked about the domain. It is one question and the answer is committed to the
        repository, so nobody has to answer it twice.

        `cordango configure` with no flags asks interactively — but **you cannot answer that prompt**,
        and it knows: run from a script or an agent it does not ask at all. Put the question in the
        conversation, then run the flag form above.

        ## Rules

        - **Ask before you model.** An entity invented to fill a silence is the most expensive thing
          in this repository, because everything else references it and nothing renames it.
        - **Never edit `.cordango/`** (the dotted directory). It is build output; your changes vanish on
          the next `cordango build`.
        - **Use stable keys.** Renaming an entity or field key is not supported yet, because nothing
          rewrites the references to it. Add and remove instead, deliberately.
        - **One aggregate per change.** It keeps diffs reviewable and is what `--scope` enforces.
        - **You do not accept your own work.** `cordango apply` writes to the working tree; a person
          reads `git diff` and stages it. Do not commit unless you are asked to.
        - Run `cordango fmt` if you hand-edited a file and the formatting drifted.
        """;
}
