// {{AppName}} — generated by Cordango from an App Definition, and yours from here on.
//
// This is an ordinary Node application. Nothing in it phones home, nothing requires the tool that
// produced it, and every file below is one you can read, edit and deploy anywhere Node runs.
// Regenerating overwrites the files it wrote before; anything you add of your own is left alone,
// and cordango.build.json lists exactly which files those are.

import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  JsonApiMessages,
  LocalFileStore,
  createApp,
  openDatabase,
  runSeed,
} from "@cordango/standalone";

import { buildRuntime } from "./app.js";
import { mountRoutes } from "./routes.js";

const here = dirname(fileURLToPath(import.meta.url));

// Empty counts as absent. An environment that sets a variable to "" has not configured it, and `??`
// would treat the empty string as a value — which turns a clear "no signing secret" into a session
// cookie signed under nothing.
function setting(name: string): string | null {
  const value = process.env[name];
  return value === undefined || value === "" ? null : value;
}

/**
 * The key every cookie in this application is signed under.
 *
 * There is no default and there cannot be one. A generated application shipping with a known
 * signing key is a generated application anybody can forge a session for, and a randomly generated
 * one would sign everybody out on every restart and every second instance. So it is required, and
 * the message says how to make one.
 */
const secret = setting("APP_SECRET");
if (secret === null) {
  console.error(
    "APP_SECRET is not set. It signs the session and antiforgery cookies, so this application "
      + "will not start without one.\n\n"
      + "  Generate one:  node -e \"console.log(require('crypto').randomBytes(32).toString('base64url'))\"\n"
      + "  Then set it:   APP_SECRET=<the value>\n\n"
      + "Keep it out of the repository and keep it stable: changing it signs everybody out.",
  );
  process.exit(1);
}

// Set SECURITY_REQUIRE_HTTPS=true once there is TLS in front of this. It marks the session and
// antiforgery cookies Secure — which a browser will not send back over plain HTTP, so turning it on
// too early makes sign-in fail with no visible reason.
const secure = setting("SECURITY_REQUIRE_HTTPS") === "true";

/**
 * The database.
 *
 * With DATABASE_URL set this is a real PostgreSQL server. Without one it is PGlite, in this
 * process, on the local disk — which is what makes `npm start` a complete application with nothing
 * to install first. Both speak the same dialect, so nothing above this line knows which it got.
 */
const driver = await openDatabase(setting("DATABASE_URL") ?? undefined);

const runtime = buildRuntime({
  appKey: "{{AppKey}}",
  appName: "{{AppName}}",
  driver,
  secret,
  secure,
  messages: new JsonApiMessages(join(here, "resources")),
});

// The schema, on the way up, so the first launch of a fresh checkout is one command and not two.
// Every statement is CREATE TABLE IF NOT EXISTS, so a restart over an existing database changes
// nothing.
try {
  await runtime.start();
} catch (failure) {
  // A driver's own message names a socket and a port and reads like a bug in this application. The
  // cause is almost always that nothing is listening yet, and the fix is one command.
  console.error(
    "Could not reach the database. Start it with `docker compose up -d db` and run this again, "
      + "or set DATABASE_URL to point somewhere that is listening.",
    failure,
  );
  process.exit(1);
}

// Demo data BEFORE the administrator, and the order is load-bearing. Seeding only ever writes into
// an EMPTY table, and creating the first administrator puts a row in the directory — so doing it
// the other way round leaves the directory holding one person and every seeded record pointing at
// people who were never created.
if (setting("SEED_ENABLED") === "true")
  await runSeed(runtime, join(here, "seed", "seed.json"), setting("SEED_DATE"));

// An administrator from the environment, for a deployment whose first visitor will not be you.
// Without it the first person to open the application is asked to create one — see the note on the
// setup route for why that window is not a hole.
await runtime.ensureAdministrator(setting("ADMIN_EMAIL"), setting("ADMIN_PASSWORD"));

const app = createApp({
  runtime,
  files: new LocalFileStore(setting("STORAGE_PATH") ?? join(here, "..", "..", "appdata", "media")),
  // The built single-page app, served from the same origin as the API. Same origin is what makes
  // the session cookie work with no CORS and the antiforgery token readable by the page.
  staticRoot: setting("WEB_ROOT") ?? join(here, "..", "public"),
  routes: mountRoutes,
});

const port = Number(setting("PORT") ?? "5000");

app.listen(port, () => {
  console.log(`{{AppName}} is listening on http://localhost:${port}`);
});

// A container stop sends SIGTERM. Closing the pool rather than being killed means an in-flight
// query finishes and PGlite flushes what it is holding, instead of the next start replaying a
// write-ahead log.
for (const signal of ["SIGTERM", "SIGINT"] as const)
  process.on(signal, () => {
    void driver.close().finally(() => process.exit(0));
  });
