using Cordango.Standalone.Hosting;
using Cordango.Standalone.Http;
using Cordango.Standalone.Mcp;
using Cordango.Standalone.Media;
using Cordango.Standalone.Directory;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Scalar.AspNetCore;
using {{AppNamespace}};
using {{AppNamespace}}.Data;
using {{AppNamespace}}.Identity;

// {{AppName}} — generated by Cordango from an App Definition, and yours from here on.
//
// This is an ordinary ASP.NET Core application. Nothing in it phones home, nothing requires the
// tool that produced it, and every file below is one you can read, edit and deploy anywhere .NET
// runs. Regenerating overwrites the files it wrote before; anything you add of your own is left
// alone, and cordango.build.json lists exactly which files those are.

var builder = WebApplication.CreateBuilder(args);

// Empty counts as absent. appsettings.json ships the key with an empty value so that the shape of
// the configuration is visible, and `??` does not treat "" as missing — which turns a clear "no
// connection string" into a Npgsql parse error twenty frames deeper.
var connectionString = builder.Configuration.GetConnectionString("Database") is { Length: > 0 } configured
    ? configured
    : throw new InvalidOperationException(
        "No connection string. Set ConnectionStrings__Database in the environment, "
        + "or ConnectionStrings:Database in appsettings.");

// The application's own data, and the sign-in tables, in one database and two contexts. Two,
// because the identity schema belongs to ASP.NET Core Identity and evolves on its own release
// schedule — keeping its migrations separate from yours means an Identity upgrade never appears as
// a change to your tables.
builder.Services.AddDbContext<AppDbContext>(options => options.UseNpgsql(connectionString));
builder.Services.AddDbContext<AppIdentityDbContext>(options => options.UseNpgsql(connectionString));

// The runtime asks for the base type; your own code asks for AppDbContext. Both have to reach the
// SAME instance — registering AppDbContext twice would give a request two change trackers and two
// connections, and a hook's pending changes would be invisible to the save that was meant to
// include them.
builder.Services.AddScoped<Cordango.Standalone.Data.CordangoDbContext>(
    services => services.GetRequiredService<AppDbContext>());

builder.Services.AddCordangoRuntime(options =>
{
    // Set Security__RequireHttps=true once there is TLS in front of this. It marks the session and
    // antiforgery cookies Secure and switches to the hardened __Host- cookie name — which a browser
    // refuses over plain HTTP, so turning it on too early makes sign-in fail with no visible reason.
    options.RequireHttps = builder.Configuration.GetValue("Security:RequireHttps", false);
});
builder.Services.AddAppIdentity(builder.Configuration.GetValue("Security:RequireHttps", false));

// The built-in directory: people, departments, groups, organizations, contacts.
builder.Services.AddDirectory();

// This application's own entities. Generated — see AppSetup.cs.
builder.Services.AddApp();

builder.Services.AddSingleton<IFileStore>(new LocalFileStore(
    builder.Configuration["Storage:Path"] is { Length: > 0 } storage
        ? storage
        : Path.Combine(builder.Environment.ContentRootPath, "..", "appdata", "media")));

// The key ring that protects the session and antiforgery cookies, kept where a redeployment cannot
// take it with it.
//
// ASP.NET Core's default is the user's home directory, which in a container is INSIDE the container
// and is replaced every time the image is rebuilt. The symptom is easy to misread as an application
// bug: after `docker compose up` everybody is signed out, and the first POST from a tab that was
// already open is refused with "your session token is out of date". Nothing logs an error, because
// nothing went wrong — the keys those cookies were written with simply no longer exist.
//
// The application NAME is pinned too. It is part of the purpose string every value is protected
// with, and it defaults to the content root path — so moving the application, or running it from a
// different directory, would invalidate every cookie for no reason a person could see.
var keyRing = builder.Configuration["Storage:Keys"] is { Length: > 0 } keys
    ? keys
    : Path.Combine(builder.Environment.ContentRootPath, "..", "appdata", "keys");

// Fully qualified: `using Cordango.Standalone.Directory` (people, departments) shadows System.IO.
System.IO.Directory.CreateDirectory(keyRing);

builder.Services.AddDataProtection()
    .PersistKeysToFileSystem(new DirectoryInfo(keyRing))
    .SetApplicationName("{{AppKey}}");

builder.Services.AddSingleton<IApiMessages>(services => new JsonApiMessages(
    services.GetRequiredService<IHttpContextAccessor>(),
    Path.Combine(AppContext.BaseDirectory, "Resources")));

// How this application describes itself.
//
// The framework finds the ROUTES by walking the controllers, which is why an endpoint you add by
// hand appears without being registered here. It cannot find the SHAPES: every record route takes a
// JsonElement, so reflection would describe each one as "an object", and a document that says that
// about every field is worse than none. OpenApiFromSchema fills them in from AppSchema.cs, which was
// emitted from the same definition as your entities.
builder.Services.AddOpenApi(options => options.AddDocumentTransformer<OpenApiFromSchema>());

// The MCP endpoint, on by default.
//
// It is not a second permission model. Every tool it offers projects an operation this application
// already has, through the same gateway the controllers use, so an AI client acting as somebody
// reaches exactly what that person reaches and is refused in the same words. Delete this line and
// the MapCordangoMcp below to turn it off.
builder.Services.AddCordangoMcp(AppSchema.Catalogue);

var app = builder.Build();

// Schema first, on the way up, so the first launch of a fresh checkout is one command and not two.
// The migrations are files in this repository — read them, edit them, review them in a pull request.
// After this build the application evolves the way any EF project does:
// `dotnet ef migrations add SomeChange`.
await using (var scope = app.Services.CreateAsyncScope())
{
    try
    {
        await scope.ServiceProvider.GetRequiredService<AppDbContext>().Database.MigrateAsync();
        await scope.ServiceProvider.GetRequiredService<AppIdentityDbContext>().Database.MigrateAsync();
    }
    catch (Npgsql.NpgsqlException failure)
    {
        // Npgsql's own message names a socket and a port and reads like a bug in the application.
        // The cause is almost always that nothing is listening yet, and the fix is one command.
        app.Logger.LogCritical(
            failure,
            "Could not reach the database. Start it with `docker compose up -d db` and run this again, "
            + "or set ConnectionStrings__Database to point somewhere that is listening.");
        return;
    }

    // Demo data BEFORE the administrator, and the order is load-bearing. Seeding only ever writes
    // into an EMPTY table, and creating the first administrator puts a row in the directory — so
    // doing it the other way round leaves the directory holding one person and every seeded record
    // pointing at people who were never created.
    if (builder.Configuration.GetValue("Seed:Enabled", false))
    {
        await Cordango.Standalone.Data.SeedRunner.RunAsync(
            scope.ServiceProvider,
            Path.Combine(AppContext.BaseDirectory, "Seed", "seed.json"),
            builder.Configuration["Seed:Date"]);
    }

    await IdentitySetup.EnsureAdministratorAsync(scope.ServiceProvider, builder.Configuration);
}

// Early, so that everything after it answers errors in the {code, error} shape and every safe
// request carries the antiforgery token the browser will need for the next unsafe one.
app.UseCordangoRuntime();

// Behind a reverse proxy that terminates TLS, the application sees plain HTTP unless the proxy's
// X-Forwarded-Proto is honoured — and then every "is this request secure" decision below is wrong.
if (builder.Configuration.GetValue("Security:BehindProxy", false))
{
    app.UseForwardedHeaders(new ForwardedHeadersOptions
    {
        ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto,
    });
}

app.UseDefaultFiles();
app.UseStaticFiles();

app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

// The document, and something to read it with. Both are real endpoints, so they win over the
// single-page fallback below; both sit OUTSIDE /api, so the catch-all that 404s unknown API routes
// never sees them.
//
// DisableDefaultFonts is not a style choice. Scalar ships its own JavaScript and CSS in the package,
// but its default typography is fetched from a font CDN — one outbound request per visit, from an
// application somebody may well have installed precisely because it does not make any. Off, it
// renders from what is already in the image and works with no route to the internet at all.
app.MapOpenApi();
app.MapScalarApiReference(options => options
    .WithTitle("{{AppName}} API")
    .DisableDefaultFonts());

// /mcp, plus the provisional server card beside it. After UseAuthentication above, so a tool call
// runs as whoever presented a credential rather than as nobody.
app.MapCordangoMcp();

// Anything that is not an API route is a page of the single-page app, and the app's router decides
// what it means. Excluding /api keeps a mistyped endpoint a 404 rather than a page of HTML that a
// fetch() will try to parse as JSON.
app.MapFallbackToFile("index.html");

app.Run();
