using Cordango.Standalone.Hosting;
using Cordango.Standalone.Http;
using Cordango.Standalone.Media;
using Cordango.Standalone.Directory;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using {{AppNamespace}};
using {{AppNamespace}}.Data;
using {{AppNamespace}}.Identity;

// {{AppName}} — generated by Cordango from an App Definition, and yours from here on.
//
// This is an ordinary ASP.NET Core application. Nothing in it phones home, nothing requires the
// tool that produced it, and every file below is one you can read, edit and deploy anywhere .NET
// runs. Regenerating overwrites the files it wrote before; anything you add of your own is left
// alone, and cordango.build.json lists exactly which files those are.

var builder = WebApplication.CreateBuilder(args);

// Empty counts as absent. appsettings.json ships the key with an empty value so that the shape of
// the configuration is visible, and `??` does not treat "" as missing — which turns a clear "no
// connection string" into a Npgsql parse error twenty frames deeper.
var connectionString = builder.Configuration.GetConnectionString("Database") is { Length: > 0 } configured
    ? configured
    : throw new InvalidOperationException(
        "No connection string. Set ConnectionStrings__Database in the environment, "
        + "or ConnectionStrings:Database in appsettings.");

// The application's own data, and the sign-in tables, in one database and two contexts. Two,
// because the identity schema belongs to ASP.NET Core Identity and evolves on its own release
// schedule — keeping its migrations separate from yours means an Identity upgrade never appears as
// a change to your tables.
builder.Services.AddDbContext<AppDbContext>(options => options.UseNpgsql(connectionString));
builder.Services.AddDbContext<AppIdentityDbContext>(options => options.UseNpgsql(connectionString));

// The runtime asks for the base type; your own code asks for AppDbContext. Both have to reach the
// SAME instance — registering AppDbContext twice would give a request two change trackers and two
// connections, and a hook's pending changes would be invisible to the save that was meant to
// include them.
builder.Services.AddScoped<Cordango.Standalone.Data.CordangoDbContext>(
    services => services.GetRequiredService<AppDbContext>());

builder.Services.AddCordangoRuntime(options =>
{
    // Set Security__RequireHttps=true once there is TLS in front of this. It marks the session and
    // antiforgery cookies Secure and switches to the hardened __Host- cookie name — which a browser
    // refuses over plain HTTP, so turning it on too early makes sign-in fail with no visible reason.
    options.RequireHttps = builder.Configuration.GetValue("Security:RequireHttps", false);
});
builder.Services.AddAppIdentity(builder.Configuration.GetValue("Security:RequireHttps", false));

// The built-in directory: people, departments, groups, organizations, contacts.
builder.Services.AddDirectory();

// This application's own entities. Generated — see AppSetup.cs.
builder.Services.AddApp();

builder.Services.AddSingleton<IFileStore>(new LocalFileStore(
    builder.Configuration["Storage:Path"] is { Length: > 0 } storage
        ? storage
        : Path.Combine(builder.Environment.ContentRootPath, "..", "appdata", "media")));

builder.Services.AddSingleton<IApiMessages>(services => new JsonApiMessages(
    services.GetRequiredService<IHttpContextAccessor>(),
    Path.Combine(AppContext.BaseDirectory, "Resources")));

var app = builder.Build();

// Schema first, on the way up, so the first launch of a fresh checkout is one command and not two.
// The migrations are files in this repository — read them, edit them, review them in a pull request.
// After this build the application evolves the way any EF project does:
// `dotnet ef migrations add SomeChange`.
await using (var scope = app.Services.CreateAsyncScope())
{
    try
    {
        await scope.ServiceProvider.GetRequiredService<AppDbContext>().Database.MigrateAsync();
        await scope.ServiceProvider.GetRequiredService<AppIdentityDbContext>().Database.MigrateAsync();
    }
    catch (Npgsql.NpgsqlException failure)
    {
        // Npgsql's own message names a socket and a port and reads like a bug in the application.
        // The cause is almost always that nothing is listening yet, and the fix is one command.
        app.Logger.LogCritical(
            failure,
            "Could not reach the database. Start it with `docker compose up -d db` and run this again, "
            + "or set ConnectionStrings__Database to point somewhere that is listening.");
        return;
    }

    // Demo data BEFORE the administrator, and the order is load-bearing. Seeding only ever writes
    // into an EMPTY table, and creating the first administrator puts a row in the directory — so
    // doing it the other way round leaves the directory holding one person and every seeded record
    // pointing at people who were never created.
    if (builder.Configuration.GetValue("Seed:Enabled", false))
    {
        await Cordango.Standalone.Data.SeedRunner.RunAsync(
            scope.ServiceProvider,
            Path.Combine(AppContext.BaseDirectory, "Seed", "seed.json"),
            builder.Configuration["Seed:Date"]);
    }

    await IdentitySetup.EnsureAdministratorAsync(scope.ServiceProvider, builder.Configuration);
}

// Early, so that everything after it answers errors in the {code, error} shape and every safe
// request carries the antiforgery token the browser will need for the next unsafe one.
app.UseCordangoRuntime();

// Behind a reverse proxy that terminates TLS, the application sees plain HTTP unless the proxy's
// X-Forwarded-Proto is honoured — and then every "is this request secure" decision below is wrong.
if (builder.Configuration.GetValue("Security:BehindProxy", false))
{
    app.UseForwardedHeaders(new ForwardedHeadersOptions
    {
        ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto,
    });
}

app.UseDefaultFiles();
app.UseStaticFiles();

app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

// Anything that is not an API route is a page of the single-page app, and the app's router decides
// what it means. Excluding /api keeps a mistyped endpoint a 404 rather than a page of HTML that a
// fetch() will try to parse as JSON.
app.MapFallbackToFile("index.html");

app.Run();
